version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-orm
    working_dir: /
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  php:
    image: git.m0vie.in:5050/reg/php8/dev:latest
    container_name: php-fpm-orm
    volumes:
      - ./:/var/www/html/

  mariadb:
    image: mariadb:latest
    container_name: mariadb-orm
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=a
      - MYSQL_PASSWORD=a
    volumes:
      - ./mariadb/data:/var/lib/mysql
